// Generated by CoffeeScript 1.3.3

/*
#   GET home page.
*/


(function() {

  exports.index = function(req, res) {
    return res.render('index');
  };

  exports.yc = function(req, res) {
    return res.render('yc');
  };

}).call(this);
